MOTDPopUpText: ""
MOTDText: "Join the project Discord: https://discord.gg/yrZRHJaAUg"
PatchNotesCommitsUrl: https://api.github.com/repos/Zheneq/EvoS/commits?per_page=100
AdminChannelWebhook: "" # Discord Webhook for admin reports
ChannelWebhook: "" # Discord Webhook for gameresults