MOTDPopUpText: ""
MOTDText: "Join the project Discord: https://discord.gg/yrZRHJaAUg"
PatchNotesCommitsUrl: https://api.github.com/repos/Zheneq/EvoS/commits?per_page=10
EnableTrustWar: true
TrustWarGamePlayedPoints: 5
TrustWarGameWonPoints: 10
GroupConfig:
  MaxGroupSize: 4
  InviteTimeout: 00:00:20
  CanInviteActiveOpponents: false
Discord:
  Enabled: false
  BotToken: "" # Enter the bots token leave empty to disable
  BotChannelId: 0 # Enter the channel id for 2way chat (usualy the LobbyChannel id)
  AdminChannel: # Discord Webhook for admin reports
    Webhook: ""
    ThreadId: # leave empty to post into the channel
  AdminEnableUserReports: true
  AdminUserReportThreadId:
  AdminEnableChatAudit: true
  AdminChatAuditThreadId:
  AdminEnableLog: false
  AdminLogThreadId: 
  GameLogChannel:
    Webhook: "" # Discord Webhook for game results
    ThreadId: 
  LobbyChannel:
    Webhook: "" # Discord Webhook for lobby status and chat
    ThreadId:
  LobbyEnableChat: true
  LobbyEnableServerStatus: true
  LobbyChannelUpdatePeriodSeconds: 300
  LobbyChannelUpdateOnChangeOnly: true